# Generated by Django 4.1 on 2022-08-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0003_alter_subject_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='password',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teachers',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
