# Generated by Django 4.1 on 2022-08-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_admin', '0004_teachers_password_alter_teachers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='permission',
            field=models.BooleanField(default=False),
        ),
    ]
